[tool.poetry]
name = "api"
version = "0.1.0"
description = ""
authors = ["Mateus <matbarbieri8@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
psycopg = "^3.1.16"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
